// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello-world-request.proto

#include "hello-world-request.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace cpp {
        template <typename>
PROTOBUF_CONSTEXPR HelloWorldRequest::HelloWorldRequest(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.name_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
    } {}
struct HelloWorldRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HelloWorldRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HelloWorldRequestDefaultTypeInternal() {}
  union {
    HelloWorldRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HelloWorldRequestDefaultTypeInternal _HelloWorldRequest_default_instance_;
}  // namespace cpp
static ::_pb::Metadata file_level_metadata_hello_2dworld_2drequest_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_hello_2dworld_2drequest_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_hello_2dworld_2drequest_2eproto = nullptr;
const ::uint32_t TableStruct_hello_2dworld_2drequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::cpp::HelloWorldRequest, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::cpp::HelloWorldRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::cpp::HelloWorldRequest, _impl_.name_),
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::cpp::HelloWorldRequest)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::cpp::_HelloWorldRequest_default_instance_._instance,
};
const char descriptor_table_protodef_hello_2dworld_2drequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\031hello-world-request.proto\022\003cpp\"!\n\021Hell"
    "oWorldRequest\022\014\n\004name\030\001 \001(\t"
};
static ::absl::once_flag descriptor_table_hello_2dworld_2drequest_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_hello_2dworld_2drequest_2eproto = {
    false,
    false,
    67,
    descriptor_table_protodef_hello_2dworld_2drequest_2eproto,
    "hello-world-request.proto",
    &descriptor_table_hello_2dworld_2drequest_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_hello_2dworld_2drequest_2eproto::offsets,
    file_level_metadata_hello_2dworld_2drequest_2eproto,
    file_level_enum_descriptors_hello_2dworld_2drequest_2eproto,
    file_level_service_descriptors_hello_2dworld_2drequest_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_hello_2dworld_2drequest_2eproto_getter() {
  return &descriptor_table_hello_2dworld_2drequest_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_hello_2dworld_2drequest_2eproto(&descriptor_table_hello_2dworld_2drequest_2eproto);
namespace cpp {
// ===================================================================

class HelloWorldRequest::_Internal {
 public:
  using HasBits = decltype(std::declval<HelloWorldRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(HelloWorldRequest, _impl_._has_bits_);
  static void set_has_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

HelloWorldRequest::HelloWorldRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cpp.HelloWorldRequest)
}
HelloWorldRequest::HelloWorldRequest(const HelloWorldRequest& from) : ::google::protobuf::Message() {
  HelloWorldRequest* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.name_){},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.name_.Set(from._internal_name(), _this->GetArenaForAllocation());
  }

  // @@protoc_insertion_point(copy_constructor:cpp.HelloWorldRequest)
}
inline void HelloWorldRequest::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.name_){},
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
HelloWorldRequest::~HelloWorldRequest() {
  // @@protoc_insertion_point(destructor:cpp.HelloWorldRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void HelloWorldRequest::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
}
void HelloWorldRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void HelloWorldRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:cpp.HelloWorldRequest)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.name_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* HelloWorldRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 34, 2> HelloWorldRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HelloWorldRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_HelloWorldRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional string name = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(HelloWorldRequest, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string name = 1;
    {PROTOBUF_FIELD_OFFSET(HelloWorldRequest, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\25\4\0\0\0\0\0\0"
    "cpp.HelloWorldRequest"
    "name"
  }},
};

::uint8_t* HelloWorldRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cpp.HelloWorldRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "cpp.HelloWorldRequest.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cpp.HelloWorldRequest)
  return target;
}

::size_t HelloWorldRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cpp.HelloWorldRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string name = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData HelloWorldRequest::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    HelloWorldRequest::MergeImpl
};
const ::google::protobuf::Message::ClassData*HelloWorldRequest::GetClassData() const { return &_class_data_; }


void HelloWorldRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<HelloWorldRequest*>(&to_msg);
  auto& from = static_cast<const HelloWorldRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cpp.HelloWorldRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_name(from._internal_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HelloWorldRequest::CopyFrom(const HelloWorldRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cpp.HelloWorldRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool HelloWorldRequest::IsInitialized() const {
  return true;
}

void HelloWorldRequest::InternalSwap(HelloWorldRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, lhs_arena,
                                       &other->_impl_.name_, rhs_arena);
}

::google::protobuf::Metadata HelloWorldRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_hello_2dworld_2drequest_2eproto_getter, &descriptor_table_hello_2dworld_2drequest_2eproto_once,
      file_level_metadata_hello_2dworld_2drequest_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace cpp
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::cpp::HelloWorldRequest*
Arena::CreateMaybeMessage< ::cpp::HelloWorldRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cpp::HelloWorldRequest >(arena);
}
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
